---
abstract: 'fast, no spec getopt'
author:
  - 'Rodrigo de Oliveira <rodrigolive@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Getopt-Mini
requires:
  perl: 5.006
  utf8::all: 0
resources:
  bugtracker: git://github.com/rodrigolive/getopt-mini.git/issues
  homepage: http://search.cpan.org/dist/Getopt-Mini/
  repository: git://github.com/rodrigolive/getopt-mini.git
version: 0.02
